# Site settings
title: 
header-img: img/home-bg.png
email: eparie@bu.edu
copyright_name: elaineparie
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  elaineparie
learn_profile: elaineparie
email_username: eparie@bu.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
